# Generated by Django 6.0.1 on 2026-02-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0003_alter_taskgroup_options_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='blogpage.profile'),
            preserve_default=False,
        ),
    ]
