# Generated by Django 6.0.1 on 2026-02-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0005_alter_task_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='blogpage.profile'),
        ),
    ]
