# Generated by Django 6.0.1 on 2026-03-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0007_task_created_on_task_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
