# Generated by Django 6.0.1 on 2026-03-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0008_task_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_image',
        ),
    ]
